name: my_tourism_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase core & services
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_database: ^12.0.0
  share_plus: ^10.0.2
  cloud_firestore: ^6.0.0

  # Social sign-ins (optional)
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2

  # ✅ Settings page
  shared_preferences: ^2.3.2

  # ✅ URL Launcher
  url_launcher: ^6.3.2

  # ✅ Biometric / PIN lock
  local_auth: ^2.3.0

  # ✅ Image Picker for profile photo
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ✅ यह लाइन सही जगह होनी चाहिए

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"   # ✅ अपना logo यहाँ डालो (PNG होना चाहिए)

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/BiharDistrictsImages/
    - assets/AndhraPradeshDistrictsImages/
    - assets/ArunachalPradeshDistrictsImages/
    - assets/AssamDistrictsImages/
    - assets/ChhattisgarhDistrictsImages/
    - assets/GujaratDistrictsImages/
    - assets/HaryanaDistrictsImages/
    - assets/HimachalPradeshDistrictsImages/
    - assets/JharkhandDistrictsImages/
    - assets/KarnatakaDistrictsImages/
    - assets/KeralaDistrictsImages/
    - assets/MadhyaPradeshDistrictsImages/
    - assets/UttarPradeshDistrictsImages/
    - assets/MaharashtraDistrictsImages/
    - assets/ManipurDistrictsImages/
    - assets/MeghalayaDistrictsImages/
    - assets/MizoramDistrictsImages/
    - assets/NagalandDistrictsImages/
    - assets/TelanganaDistrictsImages/
    - assets/PunjabDistrictsImages/
    - assets/OdishaDistrictsImages/
    - assets/SikkimDistrictsImages/
    - assets/TamilNaduDistrictsImages/
    - assets/TripuraDistrictsImages/
    - assets/UttarakhandDistrictsImages/
    - assets/RajasthanDistrictsImages/
    - assets/WestBengalDistrictsImages/
    - assets/AndamanNicobarDistrictsImages/
    - assets/DamanDiuDistrictsImages/
    - assets/DelhiDistrictsImages/
    - assets/JammuKashmirDistrictsImages/
    - assets/LadakhDistrictsImages/
    - assets/PuducherryDistrictsImage/
    - assets/LakshadweepDistrictsImages/

