// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqECS5MPUukKzmYnAV5-CwIeEm9a3ycbo',
    appId: '1:742338727018:web:777f18a860294bb0e7ce13',
    messagingSenderId: '742338727018',
    projectId: 'mytourismapp-907d2',
    authDomain: 'mytourismapp-907d2.firebaseapp.com',
    databaseURL: 'https://mytourismapp-907d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mytourismapp-907d2.firebasestorage.app',
    measurementId: 'G-5XM8Z2MN75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuMpqvigciCumZDAsiDAF6mckDapHhoQE',
    appId: '1:742338727018:android:5192ea9956531adee7ce13',
    messagingSenderId: '742338727018',
    projectId: 'mytourismapp-907d2',
    databaseURL: 'https://mytourismapp-907d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mytourismapp-907d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6uAJrLYdeLRc101gAiq6nrfCUbj5eGns',
    appId: '1:742338727018:ios:b216e7190a48de97e7ce13',
    messagingSenderId: '742338727018',
    projectId: 'mytourismapp-907d2',
    databaseURL: 'https://mytourismapp-907d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mytourismapp-907d2.firebasestorage.app',
    iosClientId: '742338727018-igm185hjmt16fd1khd1bom41vj11k7t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6uAJrLYdeLRc101gAiq6nrfCUbj5eGns',
    appId: '1:742338727018:ios:b216e7190a48de97e7ce13',
    messagingSenderId: '742338727018',
    projectId: 'mytourismapp-907d2',
    databaseURL: 'https://mytourismapp-907d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mytourismapp-907d2.firebasestorage.app',
    iosClientId: '742338727018-igm185hjmt16fd1khd1bom41vj11k7t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqECS5MPUukKzmYnAV5-CwIeEm9a3ycbo',
    appId: '1:742338727018:web:700c10a49548ae08e7ce13',
    messagingSenderId: '742338727018',
    projectId: 'mytourismapp-907d2',
    authDomain: 'mytourismapp-907d2.firebaseapp.com',
    databaseURL: 'https://mytourismapp-907d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mytourismapp-907d2.firebasestorage.app',
    measurementId: 'G-85DXLEPBC6',
  );

}